### ISSUE TITLE
Provide a simple instruction to get kubeconfig file content for generic kubernetes cluster

### ISSUE THREAD

**Issue by turastory** [Azure/k8s-set-context#46]
At first it was not clear to me what 'the contents' of kubeconfig means and spent some time to find a way.

The README gives a link to the official documentation but for those who are not familiar with k8s(like me), it would be useful if they can find more explicit way to retrieve the contents of kubeconfig file, like the following:

```
cat $HOME/.kube/config
```

**Comment by OliverMKing** [comment]
The instructions link to [this](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#merging-kubeconfig-files) which explains that you can use `kubectl config view`.

**Comment by DavidGoodwin** [comment]
knowing ... `kubectl config view -o json` ...  and seeing https://github.com/Azure/k8s-set-context/blob/main/tests/expected-kubeconfig.json helps ...
