### ISSUE TITLE
Error: File not found: '/home/runner/work/_actions/azure/k8s-set-context/v3/lib/run.js'

### ISSUE THREAD

**Issue by 633kh4ck** [Azure/k8s-set-context#55]
<img width="718" alt="image" src="https://user-images.githubusercontent.com/13217806/176533785-f0d78b8e-f3bb-482f-9bfa-03a4327d6c23.png">

```bash
$ git branch --show-current
releases/v3
$ git rev-parse HEAD
52d71d28bd61f06ee5a667046a6f0d235e6de095
$ ll ./lib
-rw-rw-r--@ 1 staff  staff   947B Jun 29 23:41 exec-child.js
-rw-rw-r--@ 1 staff  staff   7.8M Jun 29 23:41 index.js
```

**Comment by 633kh4ck** [comment]
This happened due to an implicit (breaking) change of the build system in the external action's repo that is being referenced using branch name – [OliverMKing/javascript-release-workflow@`e05502e`](https://github.com/OliverMKing/javascript-release-workflow/commit/e05502e802f9cb9fc8f3541a201212dadfa2b826#diff-6d2776058621d57e67ee850e7db85691f8747f8bfa43021c3eb0663e78c8f2e8L38-R41):

```diff
- npm run build
+ ncc build src/run.ts -o lib
```
---
https://github.com/Azure/k8s-set-context/blob/52d71d28bd61f06ee5a667046a6f0d235e6de095/.github/workflows/release-pr.yml#L12

It's safer to reference actions using specific commits or at least fixed version numbers (i.e. tags) to avoid various problems (including unexpected behavior and security issues)

Details and examples can be found in the documentation's section for `jobs.<job_id>.steps[*].uses` field: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses

**Comment by shkarface** [comment]
We also have the same issue

**Comment by 633kh4ck** [comment]
@OliverMKing @davidgamero ping

**Comment by davidgamero** [comment]
Taking a look thanks for the ping

**Comment by davidgamero** [comment]
release has been updated with the fix, can someone give it a try?

**Comment by 633kh4ck** [comment]
> release has been updated with the fix, can someone give it a try?

Works as expected 👍🏻
