### ISSUE TITLE
Please provide normal documentation for the "kubeconfig" input

### ISSUE THREAD

**Issue by Jtalk** [Azure/k8s-set-context#6]
It says:
`(Relevant for kubeconfig approach) Configuration file to be used with kubectl`

But in reality it expects the contents of my kubeconfig, not the path. More often than not, the words "configuration file" mean a file path. 

Lots of k8s platforms provide kubeconfig as a file through their CLI, so it feels natural to feed it to your action, which in turn usually leads to 2 hours of debugging & cursing. Your other actions stating calling k8s-set-context is mandatory are not helping at all. 

Perhaps you could support a file name through a separate input. `SetKubeConfigEx`?

**Comment by ds-ms** [comment]
The idea behind this is to use the secrets feature to upload your `kubeconfig` and use it.  This is mainly to support those cases where "committing your kubeconfig to your repo" can be avoided.
Here's the example provided: https://github.com/Azure/k8s-set-context#kubeconfig-approach 

If you already have brought in your KUBECONFIG using a tool, in your CI; they generally tend to achieve whatever this action is going to do. Using this action in your CI is redundant.

**Comment by Jtalk** [comment]
So we’re on the same page, great! Let’s put it in the readme in a recognisable and explicit manner, so that to spare other people a few hours’ debugging these actions. 

Cheers

**Comment by ds-ms** [comment]
I wasn't sure if it was confusing in the first place. The example talks about how you need to add it to the secrets as well. It never speaks about using a path instead. 

Do you have any specific recommendations as to what is missing? Perhaps you could raise a PR for the same?

**Comment by Jtalk** [comment]
At the very least I'd say amend the README table entry for kubeconfig: 
`(Relevant for kubeconfig approach) Configuration file to be used with kubectl` -> `(Relevant for kubeconfig approach) Contents of the configuration file to be used with kubectl (e.g. from a secret)`

... and the input description in yml:
```yaml
  kubeconfig:
    description: 'Contents of the kubeconfig file'
```

It'd also help to explain the kubeconfig approach more clearly in the README, e.g.:
> There are two approaches for specifying the deployment target:
> * Kubeconfig file provided as input to the action
>    This is roughly equivalent to:
>    ```bash
>    export KUBECONFIG=$(mktemp)
>    cat ${{ input.kubeconfig }} > $KUBECONFIG
>    [ ! -z ${{ input.context }} ] && kubectx ${{ input.context }}
>    ```



I'm not sure I can make a PR. Ain't got no msdn account and no interest in signing whatever EULA M$ might want to throw at me.

**Comment by ds-ms** [comment]
@anraghun to take this forward
