### ISSUE TITLE
Deprecation Warning for Node.js 12, update to Node.js 16

### ISSUE THREAD

**Issue by Ileriayo** [Azure/k8s-set-context#71]
The following warning arises from using: `azure/k8s-set-context@v2`
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: azure/k8s-set-context@v2

**Comment by OliverMKing** [comment]
Hi @Ileriayo! Thanks for the issue. 

v3 of the action fixes this. You should upgrade to that. #72 fixes the documentation.
