### ISSUE TITLE
Error: File not found: '/home/runner/work/_actions/azure/k8s-set-context/v4/lib/index.js'

### ISSUE THREAD

**Issue by ChrisLovering** [Azure/k8s-set-context#88]
### What happened?

Bumped up from v3 to v4 and got the error in the title.

### Version

- [X] I am using the latest version

### Runner

github runner

### Relevant log output

https://github.com/python-discord/site/actions/runs/8231726001/job/22507717765

**Comment by ChrisLovering** [comment]
@davidgamero

I noticed in https://github.com/Azure/k8s-set-context/issues/55 you said you appreciated the ping for a similar issue to this, so I'll do the same here.

**Comment by pcornelissen** [comment]
Just updated from v3 to v4 and got the exact same thing. Another lesson to upgrade one service and not all at once... #reverting #fun

**Comment by davidgamero** [comment]
@ChrisLovering thank you for reporting this issue, i've regenerated the tag on the latest release and can now see the /lib dir on the tag's hash checkout
please let me know if you continue to have any issues

**Comment by ChrisLovering** [comment]
Can confirm that works now.

https://github.com/python-discord/site/actions/runs/8231726001/job/22525283159

Thanks for your help David.

**Comment by pcornelissen** [comment]
@davidgamero Thanks for the quick response. One small thought though:
Re-uploading another version with the save version tag is not a good idea, as it also breaks some automatic upgrade mechanisms and caching. It would be better to release a v4.1 or v5 with a small note what has been fixed, so people are not wondering why their build results changed dramatically without any update from their part.
